apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: helix
type: Opaque
stringData:
  POSTGRES_DB: helix
  POSTGRES_USER: helix
  POSTGRES_PASSWORD: helix
  DATABASE_URL: postgres://helix:helix@postgres:5432/helix
